# Stubs for discord.backoff (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class ExponentialBackoff:
    def __init__(self, base: int = ..., *, integral: bool = ...) -> None: ...
    def delay(self) -> int: ...
