# Stubs for discord.compat (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

create_task: Any

def create_future(loop: Any): ...

run_coroutine_threadsafe: Any
