from typing import Any, Optional

class File:
    fp: Any = ...
    filename: Any = ...
    def __init__(self, fp: Any, filename: Optional[Any] = ...) -> None: ...
    def open_file(self): ...
    def close(self) -> None: ...
