# Stubs for discord.mixins (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class EqualityComparable:
    def __eq__(self, other: Any): ...
    def __ne__(self, other: Any): ...

class Hashable(EqualityComparable):
    def __hash__(self): ...
