from typing import Any, Optional, Union, Dict
from .emoji import Emoji, PartialEmoji

class RawMessageDeleteEvent:
    message_id: int = ...
    channel_id: int = ...
    guild_id: Optional[int] = ...
    def __init__(self, data: Dict[str, Any]) -> None: ...

class RawBulkMessageDeleteEvent:
    message_ids: int = ...
    channel_id: int = ...
    guild_id: Optional[int] = ...
    def __init__(self, data: Dict[str, Any]) -> None: ...

class RawMessageUpdateEvent:
    message_id: int = ...
    data: Any = ...
    def __init__(self, data: Dict[str, Any]) -> None: ...

class RawReactionActionEvent:
    message_id: int = ...
    channel_id: int = ...
    user_id: int = ...
    emoji: Union[str, Emoji, PartialEmoji] = ...
    guild_id: Optional[int] = ...
    def __init__(self, data: Dict[str, Any], emoji: Union[str, Emoji, PartialEmoji]) -> None: ...

class RawReactionClearEvent:
    message_id: int = ...
    channel_id: int = ...
    guild_id: Optional[int] = ...
    def __init__(self, data: Dict[str, Any]) -> None: ...
