from .iterators import ReactionIterator
from typing import Any, Optional

class Reaction:
    message: Any = ...
    emoji: Any = ...
    count: Any = ...
    me: Any = ...
    def __init__(self, message: Any, data: Any, *, emoji: Optional[Any] = ...) -> None: ...
    @property
    def custom_emoji(self): ...
    def __eq__(self, other: Any): ...
    def __ne__(self, other: Any): ...
    def __hash__(self): ...
    def users(self, limit: Optional[Any] = ..., after: Optional[Any] = ...): ...
