from typing import Any, Dict
from .enums import RelationshipType
from .state import ConnectionState
from .user import User

class Relationship:
    type: RelationshipType = ...
    user: User = ...
    def __init__(self, state: ConnectionState, data: Dict[str, Any]) -> None: ...
    async def delete(self) -> None: ...
    async def accept(self) -> None: ...
