import datetime
from typing import Any, Optional, List
from .colour import Colour
from .guild import Guild
from .member import Member
from .mixins import Hashable
from .permissions import Permissions

class Role(Hashable):
    id: int = ...
    name: str = ...
    permissions: Permissions = ...
    guild: Guild = ...
    colour: Colour = ...
    hoist: bool = ...
    position: int = ...
    managed: bool = ...
    mentionable: bool = ...
    def __init__(self, guild: Any, state: Any, data: Any) -> None: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def is_default(self) -> bool: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def mention(self) -> str: ...
    @property
    def members(self) -> List[Member]: ...
    async def edit(self, *, reason: Optional[str] = ..., **fields: Any) -> None: ...
    async def delete(self, *, reason: Optional[str] = ...) -> None: ...
