from .channel import *
from .raw_models import *
import enum
from .activity import _ActivityTag
from .calls import GroupCall
from .embeds import Embed
from .emoji import Emoji, PartialEmoji
from .enums import ChannelType, Status
from .guild import Guild
from .member import Member
from .message import Message
from .relationship import Relationship
from .role import Role
from .user import ClientUser, User
from collections import namedtuple
from typing import Any

class ListenerType(enum.Enum):
    chunk: int = ...

Listener = namedtuple("Listener", ["type", "future", "predicate"])
log: Any

ReadyState = namedtuple("ReadyState", ["launch", "guilds"])

class ConnectionState:
    loop: Any = ...
    http: Any = ...
    max_messages: Any = ...
    dispatch: Any = ...
    chunker: Any = ...
    syncer: Any = ...
    is_bot: Any = ...
    shard_count: Any = ...
    heartbeat_timeout: Any = ...
    def __init__(
        self, dispatch: Any, chunker: Any, syncer: Any, http: Any, loop: Any, **options: Any
    ) -> None: ...
    user: Any = ...
    def clear(self) -> None: ...
    def process_listeners(self, listener_type: Any, argument: Any, result: Any) -> None: ...
    @property
    def self_id(self): ...
    @property
    def voice_clients(self): ...
    def store_user(self, data: Any): ...
    def get_user(self, id: int): ...
    def store_emoji(self, guild: Any, data: Any): ...
    @property
    def guilds(self): ...
    @property
    def emojis(self): ...
    def get_emoji(self, emoji_id: Any): ...
    @property
    def private_channels(self): ...
    def add_dm_channel(self, data: Any): ...
    def chunks_needed(self, guild: Any) -> None: ...
    def request_offline_members(self, guilds: Any) -> None: ...
    def parse_ready(self, data: Any) -> None: ...
    def parse_resumed(self, data: Any) -> None: ...
    def parse_message_create(self, data: Any) -> None: ...
    def parse_message_delete(self, data: Any) -> None: ...
    def parse_message_delete_bulk(self, data: Any) -> None: ...
    def parse_message_update(self, data: Any) -> None: ...
    def parse_message_reaction_add(self, data: Any) -> None: ...
    def parse_message_reaction_remove_all(self, data: Any) -> None: ...
    def parse_message_reaction_remove(self, data: Any) -> None: ...
    def parse_presence_update(self, data: Any): ...
    def parse_user_update(self, data: Any) -> None: ...
    def parse_channel_delete(self, data: Any) -> None: ...
    def parse_channel_update(self, data: Any): ...
    def parse_channel_create(self, data: Any): ...
    def parse_channel_pins_update(self, data: Any): ...
    def parse_channel_recipient_add(self, data: Any) -> None: ...
    def parse_channel_recipient_remove(self, data: Any) -> None: ...
    def parse_guild_member_add(self, data: Any): ...
    def parse_guild_member_remove(self, data: Any) -> None: ...
    def parse_guild_member_update(self, data: Any): ...
    def parse_guild_emojis_update(self, data: Any): ...
    def parse_guild_create(self, data: Any): ...
    def parse_guild_sync(self, data: Any) -> None: ...
    def parse_guild_update(self, data: Any) -> None: ...
    def parse_guild_delete(self, data: Any): ...
    def parse_guild_ban_add(self, data: Any) -> None: ...
    def parse_guild_ban_remove(self, data: Any) -> None: ...
    def parse_guild_role_create(self, data: Any): ...
    def parse_guild_role_delete(self, data: Any): ...
    def parse_guild_role_update(self, data: Any): ...
    def parse_guild_members_chunk(self, data: Any) -> None: ...
    def parse_voice_state_update(self, data: Any) -> None: ...
    def parse_voice_server_update(self, data: Any) -> None: ...
    def parse_typing_start(self, data: Any): ...
    def parse_relationship_add(self, data: Any) -> None: ...
    def parse_relationship_remove(self, data: Any) -> None: ...
    def get_reaction_emoji(self, data: Any): ...
    def get_channel(self, id: int): ...
    def create_message(self, channel: Any, data: Any): ...
    def receive_chunk(self, guild_id: Any): ...

class AutoShardedConnectionState(ConnectionState):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def request_offline_members(self, guilds: Any, shard_id: Any) -> None: ...
    user: Any = ...
    def parse_ready(self, data: Any) -> None: ...
