import discord.abc
from .enums import DefaultAvatar, RelationshipType, UserFlags
from typing import Any, Optional

VALID_STATIC_FORMATS: Any
VALID_AVATAR_FORMATS: Any

class Profile:
    @property
    def nitro(self): ...
    premium: Any = ...
    @property
    def staff(self): ...
    @property
    def hypesquad(self): ...
    @property
    def partner(self): ...

class BaseUser(_BaseUser):
    name: str = ...
    id: int = ...
    discriminator: Any = ...
    avatar: Any = ...
    bot: Any = ...
    def __init__(self, state: Any, data: Any) -> None: ...
    def __eq__(self, other: Any): ...
    def __ne__(self, other: Any): ...
    def __hash__(self): ...
    @property
    def avatar_url(self): ...
    def is_avatar_animated(self): ...
    def avatar_url_as(
        self, *, format: Optional[Any] = ..., static_format: str = ..., size: int = ...
    ): ...
    @property
    def default_avatar(self): ...
    @property
    def default_avatar_url(self): ...
    @property
    def mention(self): ...
    def permissions_in(self, channel: Any): ...
    @property
    def created_at(self): ...
    @property
    def display_name(self): ...
    def mentioned_in(self, message: Any): ...

class ClientUser(BaseUser):
    verified: Any = ...
    email: Any = ...
    mfa_enabled: Any = ...
    premium: Any = ...
    def __init__(self, state: Any, data: Any) -> None: ...
    def get_relationship(self, user_id: Any): ...
    @property
    def relationships(self): ...
    @property
    def friends(self): ...
    @property
    def blocked(self): ...
    def edit(self, **fields: Any) -> None: ...
    def create_group(self, *recipients: Any): ...

class User(BaseUser, discord.abc.Messageable):
    @property
    def dm_channel(self): ...
    def create_dm(self): ...
    @property
    def relationship(self): ...
    def is_friend(self): ...
    def is_blocked(self): ...
    def block(self) -> None: ...
    def unblock(self) -> None: ...
    def remove_friend(self) -> None: ...
    def send_friend_request(self) -> None: ...
    def profile(self): ...
