from typing import Any

class Converter:
    def convert(self, ctx: Any, argument: Any) -> None: ...

class IDConverter(Converter):
    def __init__(self) -> None: ...

class MemberConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class UserConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class TextChannelConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class VoiceChannelConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class CategoryChannelConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class ColourConverter(Converter):
    def convert(self, ctx: Any, argument: Any): ...

class RoleConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class GameConverter(Converter):
    def convert(self, ctx: Any, argument: Any): ...

class InviteConverter(Converter):
    def convert(self, ctx: Any, argument: Any): ...

class EmojiConverter(IDConverter):
    def convert(self, ctx: Any, argument: Any): ...

class PartialEmojiConverter(Converter):
    def convert(self, ctx: Any, argument: Any): ...

class clean_content(Converter):
    fix_channel_mentions: Any = ...
    use_nicknames: Any = ...
    escape_markdown: Any = ...
    def __init__(
        self,
        *,
        fix_channel_mentions: bool = ...,
        use_nicknames: bool = ...,
        escape_markdown: bool = ...
    ) -> None: ...
    def convert(self, ctx: Any, argument: Any): ...
