from .core import Command, GroupMixin
from typing import Any

class Paginator:
    prefix: Any = ...
    suffix: Any = ...
    max_size: Any = ...
    def __init__(self, prefix: str = ..., suffix: str = ..., max_size: int = ...) -> None: ...
    def add_line(self, line: str = ..., *, empty: bool = ...) -> None: ...
    def close_page(self) -> None: ...
    @property
    def pages(self): ...

class HelpFormatter:
    width: Any = ...
    show_hidden: Any = ...
    show_check_failure: Any = ...
    def __init__(
        self, show_hidden: bool = ..., show_check_failure: bool = ..., width: int = ...
    ) -> None: ...
    def has_subcommands(self): ...
    def is_bot(self): ...
    def is_cog(self): ...
    def shorten(self, text: Any): ...
    @property
    def max_name_size(self): ...
    @property
    def clean_prefix(self): ...
    def get_command_signature(self): ...
    def get_ending_note(self): ...
    def filter_command_list(self): ...
    context: Any = ...
    command: Any = ...
    def format_help_for(self, context: Any, command_or_bot: Any): ...
    def format(self): ...
